### ISSUE TITLE
Failed to convert from type [java.lang.String] to type [java.util.Date] for value '2021-02-12T13:02:57.907+0000

### ISSUE THREAD

**Issue by srveerla** [fortify-ps/FortifyBugTrackerUtility#49]
[Fortify_bug_4.0]$ java -jar FortifyBugTrackerUtility-4.0.jar -configFile SSCToFile.xml -SSCBaseUrl https://xyz.com/ssc -SSCUserName XXXXXX -SSCPassword XXXXXXX

org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.util.Date] for value '2021-02-12T13:02:57.907+0000'; nested exception is java.time.format.DateTimeParseException: Text '2021-02-12T13:02:57.907+0000' could not be parsed, unparsed text found at index 22
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.json.JSONMap.get(JSONMap.java:132) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.getTokenData(SSCTokenFactoryUserCredentials.java:81) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.lambda$getToken$0(SSCTokenFactoryUserCredentials.java:72) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.log4j.LogMaskingHelper$AbstractMasker.on(LogMaskingHelper.java:105) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.getToken(SSCTokenFactoryUserCredentials.java:71) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.client.ssc.connection.SSCAuthenticatingRestConnection.updateBuilder(SSCAuthenticatingRestConnection.java:86) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:207) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.connection.AbstractRestConnection.executeRequestWithFinalizedWebTarget(AbstractRestConnection.java:175) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:165) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:152) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.query.AbstractRestConnectionQuery.executeRequest(AbstractRestConnectionQuery.java:138) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.query.AbstractRestConnectionQuery.processSingleRequest(AbstractRestConnectionQuery.java:207) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:197) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:87) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.query.AbstractRestConnectionQuery.getAll(AbstractRestConnectionQuery.java:107) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.bugtracker.common.src.context.AbstractSourceContextGenerator.generateContexts(AbstractSourceContextGenerator.java:180) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.getContexts(RunProcessRunnerFromSpringConfig.java:151) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.run(RunProcessRunnerFromSpringConfig.java:81) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.processrunner.RunProcessRunnerFromCLI.run(RunProcessRunnerFromCLI.java:166) [FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.processrunner.RunProcessRunnerFromCLI.main(RunProcessRunnerFromCLI.java:359) [FortifyBugTrackerUtility-4.0.jar:?]
Caused by: java.time.format.DateTimeParseException: Text '2021-02-12T13:02:57.907+0000' could not be parsed, unparsed text found at index 22
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952) ~[?:1.8.0_282]
        at java.time.format.DateTimeFormatter.parseBest(DateTimeFormatter.java:1897) ~[?:1.8.0_282]
        at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.parseZonedDateTime(JSONConversionServiceFactory.java:72) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.parseDate(JSONConversionServiceFactory.java:68) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.convert(JSONConversionServiceFactory.java:64) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.convert(JSONConversionServiceFactory.java:61) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:385) ~[FortifyBugTrackerUtility-4.0.jar:?]
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[FortifyBugTrackerUtility-4.0.jar:?]
        ... 22 more

**Comment by miirshad** [comment]
Any work around for this issue ? This issue is coming from \fortify-client-api\common-rest\src\main\lombok\com\fortify\util\rest\json\JSONDateTimeConverter.java

**Comment by rsenden** [comment]
Should be fixed by commit 6712675075b164434d8dfaa0359ee84117414406 with updated fortify-client-api version; I'll try to publish a new release within the next couple of days
