### ISSUE TITLE
SSC returns 500

### ISSUE THREAD

**Issue by grand-wazoo** [fortify-ps/FortifyBugTrackerUtility#66]
Testing FortifyBugTrackerUtility-4.5 with SSC 20.2.0.0149. It authenticates with SSC successfully, but throws this error. Not sure where to go from here:

java.lang.RuntimeException: Error accessing remote system https://xxxxxxx/ssc:
at com.fortify.util.rest.connection.AbstractRestConnection.getUnsuccesfulResponseException(AbstractRestConnection.java:358) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.connection.AbstractRestConnection.checkResponseAndGetOutput(AbstractRestConnection.java:322) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:224) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.connection.AbstractRestConnection.executeRequestWithFinalizedWebTarget(AbstractRestConnection.java:186) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:167) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:152) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.query.AbstractRestConnectionQuery.executeRequest(AbstractRestConnectionQuery.java:141) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.query.AbstractRestConnectionQuery.processSingleRequest(AbstractRestConnectionQuery.java:209) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:200) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:90) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.util.rest.query.AbstractRestConnectionQuery.getAll(AbstractRestConnectionQuery.java:110) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.bugtracker.common.src.context.AbstractSourceContextGenerator.generateContexts(AbstractSourceContextGenerator.java:180) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.getContexts(RunProcessRunnerFromSpringConfig.java:152) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.run(RunProcessRunnerFromSpringConfig.java:81) ~[FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.processrunner.RunProcessRunnerFromCLI.run(RunProcessRunnerFromCLI.java:167) [FortifyBugTrackerUtility-4.5.jar:?]
at com.fortify.processrunner.RunProcessRunnerFromCLI.main(RunProcessRunnerFromCLI.java:361) [FortifyBugTrackerUtility-4.5.jar:?]
Caused by: java.lang.Exception: Error accessing remote system https://xxxxxxxxxx/ssc: , response contents:
{"message":"An unexpected error has occurred.","responseCode":500,"errorCode":-20000}
... 16 more

**Comment by rsenden** [comment]
In order to investigate, more details are needed. For example:

- Have you been able to run the utility successfully before? For example with a different SSC version or different configuration file?
- Is this a reproducible error; does it happen every time you run the utility, or does it happen only occasionally?
- Which configuration file are you using, and are you using the configuration file as shipped with the utility, or did you customize it?
- Are there any warnings or errors in the SSC log files?
- Which API endpoint is generating this error? For example, you can check in the Tomcat log file on the SSC server which endpoint(s) are returning an HTTP 500 error.

Please note that assistance with this utility is provided on a best effort basis and as long as it doesn't take too much time. If detailed assistance or additional research is required, please consider a paid Fortify Professional Services engagement.

**Comment by rsenden** [comment]
Closed due to inactivity
